import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider, ThemeProvider } from "@/src/context";
import { Header } from "@/src/components/header";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "CINEVA",
    description: "Generated by create next app",
};

type Language = "uk" | "en";

const getValidLang = (value?: string): Language => {
    return value === "en" ? "en" : "uk";
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const initialLang = getValidLang(cookieStore.get("lang")?.value);

    return (
        <html
            lang={initialLang}
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <ThemeProvider>
            <LanguageProvider initialLang={initialLang}>
                <main className="w-full">
                    <Header />

                    {children}
                </main>
            </LanguageProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}